Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\radisson_scraper.py", line 25, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\radisson_scraper.py", line 25, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\radisson_scraper.py", line 25, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\radisson_scraper.py", line 25, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Pyth########## radisson_scraper ##########
##########  city_element
########## radisson_scraper ##########
##########  city_element
########## radisson_scraper ##########
##########  city_element
########## radisson_scraper ##########
##########  city_element
########## radisson_scraper ##########
##########  city_element
on27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\radisson_scraper.py", line 25, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\lodebernal_scraper.py", line 28, in checkin_element
    self.clear_input(element)
  File "C:\users\indisersa\Desktop\hotels\scrapers\lodebernal_scraper.py", line 49, in clear_input
    element.send_keys(Keys.ARROW_RIGHT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\lodebernal_scraper.py", line 28, in checkin_element
    self.clear_input(element)
  File "C:\users\indisersa\Desktop\hotels\scrapers\lodebernal_scraper.py", line 49, in clear_input
    element.send_keys(Keys.ARROW_RIGHT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\lodebernal_scraper.py", line 28, in checkin_element
    self.clear_input(element)
  File "C:\users\indisersa\Desktop\hotels\scrapers\lodebernal_scraper.py", line 49, in clear_input
    element.send_keys(Keys.ARROW_RIGHT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\lodebernal_scraper.py", line 28, in checkin_element
    self.clear_input(element)
  File "C:\users\indisersa\De########## lodebernal_scraper ##########
##########  checkin_element
########## lodebernal_scraper ##########
##########  checkin_element
########## lodebernal_scraper ##########
##########  checkin_element
########## lodebernal_scraper ##########
##########  checkin_element
########## lodebernal_scraper ##########
##########  checkin_element
sktop\hotels\scrapers\lodebernal_scraper.py", line 49, in clear_input
    element.send_keys(Keys.ARROW_RIGHT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\lodebernal_scraper.py", line 28, in checkin_element
    self.clear_input(element)
  File "C:\users\indisersa\Desktop\hotels\scrapers\lodebernal_scraper.py", line 49, in clear_input
    element.send_keys(Keys.ARROW_RIGHT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\bestday_scraper.py", line 33, in city_element
    _element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\bestday_scraper.py", line 33, in city_element
    _element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\bestday_scraper.py", line 33, in city_element
    _element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\bestday_scraper.py", line 33, in city_element
    _element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\bestday_scraper.py", line 33, in city_element
    _element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\bestday_scraper.py", line 33, in city_element
    _element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\bestday_scraper.py", line 33, in city_element
    _element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\bestday_scraper.py", line 33, in city_element
    _element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\r########## bestday_scraper ##########
##########  city_element
########## bestday_scraper ##########
##########  city_element
########## bestday_scraper ##########
##########  city_element
########## bestday_scraper ##########
##########  city_element
########## bestday_scraper ##########
##########  city_element
########## bestday_scraper ##########
##########  city_element
########## bestday_scraper ##########
##########  city_element
########## bestday_scraper ##########
##########  city_element
########## bestday_scraper ##########
##########  city_element
########## bestday_scraper ##########
##########  city_element
emote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\bestday_scraper.py", line 33, in city_element
    _element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\bestday_scraper.py", line 33, in city_element
    _element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\elconventoantigua_scraper.py", line 78, in occupancy_element
    element.click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\elconventoantigua_scraper.py", line 78, in occupancy_element
    element.click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\elconventoantigua_scraper.py", line 78, in occupancy_element
    element.click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\elconventoantigua_scraper.py", line 78, in occupancy_element
    element.click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Pyth########## elconventoantigua_scraper ##########
##########  occupancy_element
########## elconventoantigua_scraper ##########
##########  occupancy_element
########## elconventoantigua_scraper ##########
##########  occupancy_element
########## elconventoantigua_scraper ##########
##########  occupancy_element
########## elconventoantigua_scraper ##########
##########  occupancy_element
on27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\elconventoantigua_scraper.py", line 78, in occupancy_element
    element.click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\expedia_scraper.py", line 38, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\expedia_scraper.py", line 38, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\expedia_scraper.py", line 38, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\expedia_scraper.py", line 38, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\expedia_scraper.py", line 38, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\expedia_scraper.py", line 38, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\expedia_scraper.py", line 38, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\expedia_scraper.py", line 38, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\we########## expedia_scraper ##########
##########  city_element
########## expedia_scraper ##########
##########  city_element
########## expedia_scraper ##########
##########  city_element
########## expedia_scraper ##########
##########  city_element
########## expedia_scraper ##########
##########  city_element
########## expedia_scraper ##########
##########  city_element
########## expedia_scraper ##########
##########  city_element
########## expedia_scraper ##########
##########  city_element
########## expedia_scraper ##########
##########  city_element
########## expedia_scraper ##########
##########  city_element
belement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\expedia_scraper.py", line 38, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\expedia_scraper.py", line 38, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 34, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 34, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 34, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 34, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 34, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 34, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 34, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 34, in city_element
    element.send_keys(self.city)
  ########## book_hotel_beds_scraper ##########
##########  city_element
########## book_hotel_beds_scraper ##########
##########  city_element
########## book_hotel_beds_scraper ##########
##########  city_element
########## book_hotel_beds_scraper ##########
##########  city_element
########## book_hotel_beds_scraper ##########
##########  city_element
########## book_hotel_beds_scraper ##########
##########  city_element
########## book_hotel_beds_scraper ##########
##########  city_element
########## book_hotel_beds_scraper ##########
##########  city_element
########## book_hotel_beds_scraper ##########
##########  city_element
########## book_hotel_beds_scraper ##########
##########  city_element
File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 34, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 34, in city_element
    element.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\hotels_scraper.py", line 31, in city_element
    self.visibility(self.driver, element, 10).send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\hotels_scraper.py", line 31, in city_element
    self.visibility(self.driver, element, 10).send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\hotels_scraper.py", line 31, in city_element
    self.visibility(self.driver, element, 10).send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\hotels_scraper.py", line 31, in city_element
    self.visibility(self.driver, element, 10).send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\hotels_scraper.py", line 31, in city_element
    self.visibility(self.driver, element, 10).send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\hotels_scraper.py", line 31, in city_element
    self.visibility(self.driver, element, 10).send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\hotels_scraper.py", line 31, in city_element
    self.visibility(self.driver, element, 10).send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", lin########## hotels_scraper ##########
##########  city_element
########## hotels_scraper ##########
##########  city_element
########## hotels_scraper ##########
##########  city_element
########## hotels_scraper ##########
##########  city_element
########## hotels_scraper ##########
##########  city_element
########## hotels_scraper ##########
##########  city_element
########## hotels_scraper ##########
##########  city_element
########## hotels_scraper ##########
##########  city_element
########## hotels_scraper ##########
##########  city_element
########## hotels_scraper ##########
##########  city_element
e 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\hotels_scraper.py", line 31, in city_element
    self.visibility(self.driver, element, 10).send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\hotels_scraper.py", line 31, in city_element
    self.visibility(self.driver, element, 10).send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\hotels_scraper.py", line 31, in city_element
    self.visibility(self.driver, element, 10).send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 52, in city_element
    element_before.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 52, in city_element
    element_before.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 52, in city_element
    element_before.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 52, in city_element
    element_before.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 52, in city_element
    element_before.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 52, in city_element
    element_before.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 52, in city_element
    element_before.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 52, in city_element
    element_before.send_keys(self.city)
  File "C:########## booking_scraper ##########
##########  city_element
########## booking_scraper ##########
##########  city_element
########## booking_scraper ##########
##########  city_element
########## booking_scraper ##########
##########  city_element
########## booking_scraper ##########
##########  city_element
########## booking_scraper ##########
##########  city_element
########## booking_scraper ##########
##########  city_element
########## booking_scraper ##########
##########  city_element
########## booking_scraper ##########
##########  city_element
########## booking_scraper ##########
##########  city_element
\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 52, in city_element
    element_before.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

Traceback (most recent call last):
  File "C:\users\indisersa\Desktop\hotels\scrapers\base_scraper.py", line 60, in error_func
    function()
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 52, in city_element
    element_before.send_keys(self.city)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 352, in send_keys
    'value': keys_to_typing(value)})
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=66.0.3359.139)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)

